# Generated by Django 3.2.9 on 2021-11-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_user_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('s', 'seller'), ('c', 'customer')], default='s', max_length=1, verbose_name='status'),
        ),
    ]
