# Generated by Django 3.2.9 on 2021-11-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211116_1420'),
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='product',
        ),
        migrations.AddField(
            model_name='basket',
            name='product',
            field=models.ManyToManyField(to='products.Product', verbose_name='product'),
        ),
    ]
