# Generated by Django 3.2.9 on 2021-11-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=120, null=True, unique=True),
        ),
    ]
