# Generated by Django 3.2.9 on 2021-11-16 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_status'),
        ('products', '0003_auto_20211116_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('desc', models.TextField(verbose_name='description')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('autor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='writer')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='post')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.comment', verbose_name='comment'),
        ),
    ]
